### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by jlqzzz** [JeffWang987/ISE-RCNN#1]
Dear Author，

Where is the paper? Can you provide the corresponding paper link?

Thank you very much！

**Comment by JeffWang987** [comment]
> Dear Author，
> 
> Where is the paper? Can you provide the corresponding paper link?
> 
> Thank you very much！

We will not make the paper public, because it is written in 2021.9 and may be outdated. However, we will update the method description and some experimental results in the README.

We open-source ISE-RCNN and hope it will make some inspiration to the 3D detection community.

**Comment by JeffWang987** [comment]
The paper is uploaded to the main branch.
